import GitHub from "github-api";
import Repository from "github-api";
import $ from "jquery";
import request from "superagent";

// ///////////////////////////////////////////////////////

// GET action of "Request" button
var $btn_request = $('#btn_request');
$btn_request.on('click', function(event) {
	test_request();
});

// /////////////////
// TEST_REQUEST
// TEST a POST request with "superagent" 
// Client_id and client_secrets are part of the OAuth Apps (https://github.com/settings/developers) 
// code is generated by the GET request of the "Login" link in the HTML content
function test_request(){
    show_loader();
    // Get the temporary code value returned by github [GET https://github.com/login/oauth/authorize]
    // https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#1-request-a-users-github-identity 
    let searchParams = new URLSearchParams(window.location.search)
    if (searchParams.has('code')) var code = searchParams.get('code');
 
    //var code = "c653300268cdb9dbd748"
    console.log(code);

    // Exchange the code for an access token with a POST request [POST https://github.com/login/oauth/access_token]
    // https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#2-users-are-redirected-back-to-your-site-by-github
    request
    .post('https://github.com/login/oauth/access_token')
    .send({ 
	  client_id: '910ed700e3586d568fc3', 
	  client_secret: '4b06553041f33c30dc922f8c20a032b9fa35f44c',
	  code: code}) // sends a JSON post body
    //.set('X-API-Key', 'foobar')
    .set('Accept', 'application/json')
    //.set('Access-Control-Allow-Origin', '*')
    .then(function (result) {
    const data = result.body
    console.log(data); //  Will be like (because of Accept: application/json) ==>  {"access_token":"e72e16c7e42f292c6912e7710c838347ae178b4a", "scope":"repo,gist", "token_type":"bearer"} 
    console.log(data['access_token']);
    const access_token=data['access_token'];
    hide_loader();
    home(access_token);
   })
   .catch(err => {
        console.log(err.message);
    	hide_loader();
	alert("We could not authentify you with the API request. Error message: \n--\t--\t--\t--\t--\t--\t--\t--\n" + err.message + "\n--\t--\t--\t--\t--\t--\t--\t--\n Please enter you gihub access_token in the the form");
	ask_token();

    });

}


// /////////////////
// ASK_TOKEN
// TODO: DOC
function ask_token(){
    var $div_access_token = $('#div_access_token');
    $div_access_token.show();
    var $btn_access_token = $('#btn_access_token');
    $btn_access_token.on('click', function(event) {
	 show_loader();
         var $access_token = $('#access_token');
	 console.log($access_token.val()); //
	 var gh = new GitHub({
	   //username: 'ValentinMarcon',
	   token: $access_token.val()
	 });
        gh.getUser().getProfile(function(err, profile) { 
		console.log("--------------------");
		console.log(profile);
		console.log("--------------------");
		hide_loader();
		if(!profile){
			alert("Authentication failure with token "+$access_token.val());
		}
		else {
			alert(profile["login"]+" connected!");
			home($access_token.val());
		}
	});

    });
}


// /////////////////
// HOME
//
// TODO: Change page and use the access_token to access github API
function home(access_token){
    console.log("tot");
    sessionStorage.setItem("access_token",access_token);
    location.href = "index_search_tool.html";
}


function show_loader(){
	var $loader = $('#search_loader');
	$loader.show();
}
function hide_loader(){
	var $loader = $('#search_loader');
	$loader.hide();
}




/*
function test2_request(){

	var https = require("https");
	var userName='ValentinMarcon';
	var options = {
	host :"github.com",
	path : '/login/oauth/access_token',  
	method : 'POST',
	client_id: '910ed700e3586d568fc3',
	client_secret:'4b06553041f33c30dc922f8c20a032b9fa35f44c',
	code:code,
		headers: {'User-Agent':'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)','Access-Control-Allow-Origin':'http://localhost:*'}
	}

	var req = https.request(options, (res) => {
	  console.log('statusCode:', res.statusCode);
	  console.log('headers:', res.headers);
	  });

	req.on('error', (e) => {
	  console.error(e);
	});

	req.write("toto");
	req.end();

}
*/





// /////////////////////////////////////////////

// OTHER TEST

/*	
postData(`https://github.com/login/oauth/access_token`, {client_id: '910ed700e3586d568fc3', 
							 client_secret: '4b06553041f33c30dc922f8c20a032b9fa35f44c',
							 code: code})
  .then(data => console.log(JSON.stringify(data))) // JSON-string from `response.json()` call
  .catch(error => console.log(error));
*/




/*
function postData(url = ``, data = {}) {
  // Default options are marked with *
    return fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        mode: "cors", // no-cors, cors, *same-origin
        cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
        //credentials: "same-origin", // include, *same-origin, omit
        headers: {
            "Content-Type": "application/json",
            //"Access-Control-Allow-Origin":"http://localhost:1234",
            //"Access-Control-Allow-Methods":"POST",
	    //"Access-Control-Allow-Credentials": true
	// "Content-Type": "application/x-www-form-urlencoded",
        },
        redirect: "follow", // manual, *follow, error
        referrer: "no-referrer", // no-referrer, *client
        body: JSON.stringify(data), // body data type must match "Content-Type" header
    })
    .then(response => response.json()); // parses JSON response into native Javascript objects
}
*/
